### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by yang-W517** [shuoyang129/image-free-multi-label-image-recognition#2]
-------------------- Building Dataset ----------------------
DATASET.ROOT = 
data_split = 
PARTIAL_PORTION= 1.000001
INPUT.SIZE = 224
Traceback (most recent call last):
  File "train_baseline.py", line 263, in <module>
    main()
  File "train_baseline.py", line 32, in main
    train_dataset = build_dataset(cfg, train_split)
  File "/media/p520/4CDA9611DA95F782/file/wzy/image-free-multi-label-image-recognition-main/dataloaders/dataset_builder.py", line 28, in build_dataset
    return MODEL_TABLE[cfg.DATASET.NAME](
KeyError: ''

When I encounter this error during training, how should I solve it?

**Comment by shzirui** [comment]
You may need to check if DATASET.ROOT, DATASET.NAME, or data_split is properly set in your configuration file.
